# Generated by Django 4.1.3 on 2022-12-03 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='books',
            options={'verbose_name': 'Book', 'verbose_name_plural': 'Books'},
        ),
    ]
